version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"    
    environment:     
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: message
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - .init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

